name: Checkstyle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # - name: Set up JDK 17
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'
    #     cache: maven
    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml

    - name: Check code style with Checkstyle
      run: mvn checkstyle:checkstyle
      
    - name: Archive HTML Checkstyle Report
      run: mvn checkstyle:checkstyle-aggregate
      env:
        REPORT_FILE: target/site/checkstyle.html
      shell: bash

    - name: Upload Checkstyle Report
      uses: actions/upload-artifact@v3
      with:
        name: checkstyle-report
        path: ${{ runner.workspace }}/${{ env.REPORT_FILE }}
