name: DependencyCheck

on:
  push:
    branches:
      - [ "master" ]
  pull_request:
    branches:
      - [ "master" ]

jobs:
  dependencycheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # - name: Set up JDK 17
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'
    #     cache: maven

    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml

    - name: Run Dependency Check
      run: mvn org.owasp:dependency-check-maven:check

    - name: Archive Dependency Check Report
      run: mvn org.owasp:dependency-check-maven:aggregate
      env:
        REPORT_FILE: target/site/dependency-check-report.html
      shell: bash

    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: ${{ runner.workspace }}/${{ env.REPORT_FILE }}
